// Helpers shared by index.html and gallery.html.
// Album data lives in gallery-data.js, generated by scripts/build_gallery.py.

const sortedAlbums = () => [...ALBUMS].sort((a, b) => b.date.localeCompare(a.date));
const isVideo = src => /\.(mp4|webm)$/i.test(src);
const fmtDate = d => {
  const [y, m] = d.split('-');
  return m ? new Date(y, m - 1).toLocaleDateString('en-US', { month: 'short', year: 'numeric' }) : y;
};
const countLabel = a => {
  const v = a.items.filter(i => isVideo(i.src)).length, p = a.items.length - v;
  return [p && `${p} photo${p > 1 ? 's' : ''}`, v && `${v} video${v > 1 ? 's' : ''}`].filter(Boolean).join(' · ');
};
const media = (src, alt = '') => isVideo(src)
  ? `<video src="${src}#t=0.1" muted playsinline preload="metadata"></video>`
  : `<img loading="lazy" src="${src}" alt="${alt}">`;
const albumCard = a => `
  <a class="card" href="gallery.html?album=${a.id}">
    <div class="cover">${media(a.cover)}<span class="count">${a.items.length}</span></div>
    <b>${a.title}</b>
    <span class="meta">${a.place ? a.place + ' · ' : ''}${fmtDate(a.date)}</span>
  </a>`;
