// Generated by scripts/build_gallery.py from media/gallery/. Do not edit by hand.
const ALBUMS = [
  {
    "id": "2023-06_icros",
    "tag": "conferences",
    "title": "ICROS 2023",
    "place": "ICROS Annual Conference",
    "date": "2023-06",
    "cover": "media/gallery/conferences/2023-06_icros/IMG_1906_Original.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2023-06_icros/IMG_1906_Original.jpeg",
        "caption": ""
      }
    ]
  },
  {
    "id": "2024-11_ksme",
    "tag": "conferences",
    "title": "KSME Conference 2024",
    "place": "Jeju, Korea",
    "date": "2024-11",
    "cover": "media/gallery/conferences/2024-11_ksme/IMG_4401.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2024-11_ksme/IMG_4401.jpeg",
        "caption": ""
      }
    ]
  },
  {
    "id": "2025-02_kroc",
    "tag": "conferences",
    "title": "KRoC 2025",
    "place": "Pyeongchang, Korea",
    "date": "2025-02",
    "cover": "media/gallery/conferences/2025-02_kroc/IMG_3568.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2025-02_kroc/IMG_3568.jpeg",
        "caption": ""
      }
    ]
  }
];
