// Generated by scripts/build_gallery.py from media/gallery/. Do not edit by hand.
const ALBUMS = [
  {
    "id": "2023-06_icros",
    "tag": "conferences",
    "title": "ICROS 2023",
    "place": "ICROS Annual Conference",
    "date": "2023-06",
    "cover": "media/gallery/conferences/2023-06_icros/IMG_1906_Original.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2023-06_icros/IMG_1906_Original.jpeg",
        "caption": ""
      }
    ]
  },
  {
    "id": "2024-11_ksme",
    "tag": "conferences",
    "title": "KSME Conference 2024",
    "place": "Jeju, Korea",
    "date": "2024-11",
    "cover": "media/gallery/conferences/2024-11_ksme/IMG_4401.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2024-11_ksme/IMG_4401.jpeg",
        "caption": ""
      }
    ]
  },
  {
    "id": "2025-02_kroc",
    "tag": "conferences",
    "title": "KRoC 2025",
    "place": "Pyeongchang, Korea",
    "date": "2025-02",
    "cover": "media/gallery/conferences/2025-02_kroc/IMG_3568.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2025-02_kroc/IMG_3568.jpeg",
        "caption": ""
      }
    ]
  },
  {
    "id": "2025-05_ksme-bio",
    "tag": "conferences",
    "title": "KSME Bio-Engineering Division 2025",
    "place": "",
    "date": "2025-05",
    "cover": "media/gallery/conferences/2025-05_ksme-bio/IMG_4075.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2025-05_ksme-bio/IMG_4040_Original.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-05_ksme-bio/IMG_4075.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-05_ksme-bio/IMG_4077.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-05_ksme-bio/IMG_4078.jpeg",
        "caption": ""
      }
    ]
  },
  {
    "id": "2025-09_corl",
    "tag": "conferences",
    "title": "CoRL 2025",
    "place": "Seoul, Korea",
    "date": "2025-09",
    "cover": "media/gallery/conferences/2025-09_corl/IMG_4583.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2025-09_corl/IMG_4574.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-09_corl/IMG_4577.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-09_corl/IMG_4579.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-09_corl/IMG_4583.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-09_corl/IMG_4594.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-09_corl/IMG_4607.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-09_corl/IMG_4610.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-09_corl/IMG_4615.jpeg",
        "caption": "bokeon ,, are you okay,,?"
      }
    ]
  },
  {
    "id": "2025-09_humanoids",
    "tag": "conferences",
    "title": "Humanoids 2025",
    "place": "Seoul, Korea",
    "date": "2025-09",
    "cover": "media/gallery/conferences/2025-09_humanoids/IMG_4719.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2025-09_humanoids/IMG_4638.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-09_humanoids/IMG_4719.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-09_humanoids/IMG_8665.jpeg",
        "caption": ""
      }
    ]
  },
  {
    "id": "2025-10_iros",
    "tag": "conferences",
    "title": "IROS 2025",
    "place": "Hangzhou, China",
    "date": "2025-10",
    "cover": "media/gallery/conferences/2025-10_iros/IMG_4878.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_4782.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_4800.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_4815.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_4819.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_4832.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_4856.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_4878.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_4898.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_4916.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_4988.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_4993.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_5019.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_5024.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_5027.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_5035.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_5039.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_5082.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_5091.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_8826.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2025-10_iros/IMG_8845.jpeg",
        "caption": ""
      }
    ]
  },
  {
    "id": "2026-02_kroc",
    "tag": "conferences",
    "title": "KRoC 2026",
    "place": "Pyeongchang, Korea",
    "date": "2026-02",
    "cover": "media/gallery/conferences/2026-02_kroc/IMG_5549.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2026-02_kroc/IMG_5481.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-02_kroc/IMG_5484.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-02_kroc/IMG_5505.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-02_kroc/IMG_5516.jpeg",
        "caption": "Hi Taehu! Nice to meet you."
      },
      {
        "src": "media/gallery/conferences/2026-02_kroc/IMG_5522.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-02_kroc/IMG_5535.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-02_kroc/IMG_5541.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-02_kroc/IMG_5549.jpeg",
        "caption": ""
      }
    ]
  },
  {
    "id": "2026-06_icra",
    "tag": "conferences",
    "title": "ICRA 2026",
    "place": "Vienna, Austria",
    "date": "2026-06",
    "cover": "media/gallery/conferences/2026-06_icra/IMG_6074.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_5925.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_5932.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_5938.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_5968.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_5983.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_5998.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6004.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6008.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6047.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6055.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6074.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6081.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6083.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6093.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6098.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6102.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6152.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6163.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6189.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6223.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6226.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6228.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6259.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6296.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6331.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6347.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6385.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6410.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6435.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6441.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6445.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-06_icra/IMG_6453.jpeg",
        "caption": ""
      }
    ]
  },
  {
    "id": "2026-07_icros",
    "tag": "conferences",
    "title": "ICROS 2026",
    "place": "Daegu, Korea",
    "date": "2026-07",
    "cover": "media/gallery/conferences/2026-07_icros/IMG_6530.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2026-07_icros/IMG_6514.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-07_icros/IMG_6522.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-07_icros/IMG_6524.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-07_icros/IMG_6526.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-07_icros/IMG_6530.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-07_icros/IMG_6536.jpeg",
        "caption": ""
      }
    ]
  },
  {
    "id": "2026-08_ifac",
    "tag": "conferences",
    "title": "IFAC World Congress 2026",
    "place": "Busan, Korea",
    "date": "2026-08",
    "cover": "media/gallery/conferences/2026-08_ifac/IMG_6754.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6724.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6725.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6727.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6728.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6730.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6731.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6741.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6744.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6746_still.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6754.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6810.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6814.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6815.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6816.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6819.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6827.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6830.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6839.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6848.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-08_ifac/IMG_6851.jpeg",
        "caption": ""
      }
    ]
  },
  {
    "id": "2026-10_iros",
    "tag": "conferences",
    "title": "IROS 2026",
    "place": "Pittsburgh, USA",
    "date": "2026-10",
    "cover": "media/gallery/conferences/2026-10_iros/IMG_2911.jpeg",
    "items": [
      {
        "src": "media/gallery/conferences/2026-10_iros/7604f78c84ac900811601223e2668b9c.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/DSCF0695.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/DSCF0705.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/DSCF0710.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/DSCF0711.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/DSCF0833.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/DSCF0889.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_2396.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_2404.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_2791.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_2837.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_2911.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_2915.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_2936.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_3093.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_3172.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_6921.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_6922.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_6924.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_6931.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_6951.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_6959.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_6966.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_6977.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_6981.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_6982.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_6984.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_6996.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7016.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7023.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7049.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7056.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7059.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7061.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7070.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7071.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7075.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7078.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7092.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7100.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7113.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7114.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7132.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7135.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7139.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7149.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7242.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7243.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7245.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7248.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7251.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7252.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7260.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7266.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7271.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7273.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7289.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7291.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7292.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7305.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7307.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7331.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7334.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7336.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7339.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7353.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7365.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7366.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7369.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7380.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7386.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7399.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7401.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7421.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7423.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7437.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7438.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7440.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7450.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7455.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7457.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7459.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7466.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7468.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7484.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7501.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7505.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7522.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7529.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7543.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7560.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7561.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7573.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7581.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7586.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7589.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7591.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7594.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7603.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7617.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7625.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7630.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7642.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7646.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7652.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7655.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7656.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7657.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7658.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7669.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7672.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7673.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7678.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7688.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7691.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7694.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7696.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7700.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7770.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7781.mp4",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7782.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7786.jpeg",
        "caption": ""
      },
      {
        "src": "media/gallery/conferences/2026-10_iros/IMG_7860.jpeg",
        "caption": ""
      }
    ]
  }
];
