#!/usr/bin/env python3
"""Scan media/gallery/ and write gallery-data.js. Run after adding photos or videos:

    python3 scripts/build_gallery.py

Layout:
    media/gallery/<category>/<YYYY-MM>_<slug>/     (or <YYYY>_<slug> for year-long albums)
        album.json   {"title": "ICRA 2026", "place": "Vienna, Austria",
                      "cover": "03.jpg", "captions": {"01.jpg": "My poster"}}   (all optional)
        *.jpg *.jpeg *.png *.webp *.gif            photos, shown in filename order
        *.mp4 *.webm                               videos

<category> is the filter tag on gallery.html: conferences | grad-school | personal.
Albums with no photos or videos are left out.
"""
import json
import re
from pathlib import Path
from urllib.parse import quote

ROOT = Path(__file__).resolve().parent.parent
GALLERY = ROOT / 'media' / 'gallery'
OUT = ROOT / 'gallery-data.js'
MEDIA = {'.jpg', '.jpeg', '.png', '.webp', '.gif', '.mp4', '.webm'}
CONVERT = {'.heic': 'jpg', '.mov': 'mp4'}
BIG = 3_000_000


def url(path):
    return quote(path.relative_to(ROOT).as_posix())


def build():
    albums = []
    for d in sorted(GALLERY.glob('*/*/')):
        m = re.match(r'(\d{4}(?:-\d{2})?)_(.+)', d.name)
        if not m:
            print(f'skip {d.relative_to(ROOT)}: folder name must look like 2026-06_icra or 2026_daily-life')
            continue
        date, slug = m.groups()
        meta_file = d / 'album.json'
        meta = json.loads(meta_file.read_text(encoding='utf-8')) if meta_file.exists() else {}

        files = []
        for f in sorted(d.iterdir()):
            ext = f.suffix.lower()
            if ext in CONVERT:
                print(f'skip {f.relative_to(ROOT)}: browsers cannot show {ext}, convert to .{CONVERT[ext]}')
            elif ext in MEDIA:
                files.append(f)
                if f.stat().st_size > BIG:
                    print(f'warn {f.relative_to(ROOT)}: {f.stat().st_size / 1e6:.1f} MB, consider resizing')
        if not files:
            continue

        captions = meta.get('captions', {})
        photos = [f for f in files if f.suffix.lower() not in {'.mp4', '.webm'}]
        cover = d / meta['cover'] if 'cover' in meta else (photos or files)[0]
        albums.append({
            'id': d.name,
            'tag': d.parent.name,
            'title': meta.get('title', slug),
            'place': meta.get('place', ''),
            'date': date,
            'cover': url(cover),
            'items': [{'src': url(f), 'caption': captions.get(f.name, '')} for f in files],
        })
    return albums


if __name__ == '__main__':
    albums = build()
    OUT.write_text(
        '// Generated by scripts/build_gallery.py from media/gallery/. Do not edit by hand.\n'
        f'const ALBUMS = {json.dumps(albums, ensure_ascii=False, indent=2)};\n',
        encoding='utf-8')
    print(f'{OUT.name}: {len(albums)} albums, {sum(len(a["items"]) for a in albums)} files')
